name       : ruby-winrm
version    : 2.3.4
release    : 4
source     :
    - https://rubygems.org/downloads/winrm-2.3.4.gem : d537b0231d33e3f4c82601894df61994a996cec13b1ba4e2b8d3c62d86db808d
license    : Apache-2.0
component  : programming.ruby
summary    : RubyGem - winrm
description: |
    Ruby library for Windows Remote Management.
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby-builder
    - ruby-erubi
    - ruby-gssapi
    - ruby-gyoku
    - ruby-httpclient
    - ruby-logging
    - ruby-nori
    - rubyntlm
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
